title: Projet MachineThatDraws - Groupe 02
description: Documentation du projet

theme: just-the-docs

url: https://makerspace-amiens.github.io/MachineThatDraws-Groupe02

just_the_docs:
  navigation_depth: 5
  search_enabled: true
  search_indexing: true
nav:
  - title: Accueil
    url: /
  - title: Objectifs
    url: /objectifs
  - title: Conception
    url: /conception
  - title: Études
    url: /etudes
  - title: Résultats
    url: /resultats
  - title: Équipe
    url: /equipe
url: https://github.com/Makerspace-Amiens


  
